import type {
  HandoffBrief,
  SynthesisResult,
  ThoughtMultiplierConfig,
} from './types.js';

export function buildBrief(
  synthesis: SynthesisResult,
  userInput: string,
  config: ThoughtMultiplierConfig,
): HandoffBrief {
  const title = extractTitle(userInput);
  const objective = extractObjective(userInput);
  const acceptanceCriteria = generateAcceptanceCriteria(synthesis);
  const doNotChange = generateDoNotChange(config.projectDoNotChange ?? []);
  const projectName = config.projectName ?? 'Project';
  const domainQuestions = synthesis.unresolvedConcerns.map(
    (c) => `${c.description} (raised by: ${c.source})`,
  );

  const markdown = generateMarkdown({
    title,
    objective,
    synthesis,
    acceptanceCriteria,
    doNotChange,
    domainQuestions,
    projectName,
  });

  return {
    requestId: synthesis.requestId,
    title,
    objective,
    steps: synthesis.buildSteps,
    acceptanceCriteria,
    doNotChange,
    domainQuestions,
    estimatedTokenCost: {
      model: config.thinkerModel,
      estimatedInput: 50_000,
      estimatedOutput: 30_000,
    },
    generatedAt: new Date(),
    thinkerContributions: synthesis.thinkerContributions,
    markdown,
  };
}

interface MarkdownArgs {
  title: string;
  objective: string;
  synthesis: SynthesisResult;
  acceptanceCriteria: string[];
  doNotChange: string[];
  domainQuestions: string[];
  projectName: string;
}

function generateMarkdown(args: MarkdownArgs): string {
  const { title, objective, synthesis, acceptanceCriteria, doNotChange, domainQuestions, projectName } = args;
  const lines: string[] = [];

  lines.push(`# CLAUDE CODE BUILD BRIEF — ${title}`);
  lines.push('');
  lines.push(`**Project:** ${projectName}`);
  lines.push(`**Generated by:** System B (Thought Multiplier)`);
  lines.push(`**Priority:** P1`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## OBJECTIVE');
  lines.push('');
  lines.push(objective);
  lines.push('');

  for (const step of synthesis.buildSteps) {
    lines.push(`## STEP ${step.order}: ${step.title}`);
    lines.push('');
    lines.push(step.description);
    lines.push('');

    if (step.files.length > 0) {
      lines.push('**Files:**');
      for (const f of step.files) lines.push(`- ${f}`);
      lines.push('');
    }
    if (step.testRequirements.length > 0) {
      lines.push('**Test requirements:**');
      for (const t of step.testRequirements) lines.push(`- ${t}`);
      lines.push('');
    }
    if (step.securityConsiderations.length > 0) {
      lines.push('**Security:**');
      for (const s of step.securityConsiderations) lines.push(`- ${s}`);
      lines.push('');
    }
  }

  lines.push('## ACCEPTANCE CRITERIA');
  lines.push('');
  for (const ac of acceptanceCriteria) lines.push(`- [ ] ${ac}`);
  lines.push('');

  lines.push('## DO NOT CHANGE');
  lines.push('');
  for (const dnc of doNotChange) lines.push(`- ${dnc}`);
  lines.push('');

  lines.push('## DOMAIN QUESTIONS');
  lines.push('');
  if (domainQuestions.length === 0) {
    lines.push('None.');
  } else {
    for (const q of domainQuestions) lines.push(`- ${q}`);
  }
  lines.push('');

  if (synthesis.resolvedConflicts.length > 0) {
    lines.push('## CONFLICT RESOLUTIONS');
    lines.push('');
    for (const conflict of synthesis.resolvedConflicts) {
      lines.push(`**${conflict.thinkerA} vs ${conflict.thinkerB}** — ${conflict.issue}`);
      lines.push(`- ${conflict.thinkerA}: ${conflict.positionA}`);
      lines.push(`- ${conflict.thinkerB}: ${conflict.positionB}`);
      if (conflict.resolution) {
        lines.push(`- **Resolution:** ${conflict.resolution.reasoning}`);
      }
      lines.push('');
    }
  }

  const contributors = Object.keys(synthesis.thinkerContributions);
  if (contributors.length > 0) {
    lines.push('## THINKER CONTRIBUTIONS');
    lines.push('');
    for (const role of contributors) {
      const analysis = synthesis.thinkerContributions[role as keyof typeof synthesis.thinkerContributions];
      if (!analysis) continue;
      lines.push(`**${role}:** ${analysis}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

export function extractTitle(input: string): string {
  const words = input.trim().split(/\s+/).slice(0, 8).join(' ');
  if (!words) return 'Untitled Build';
  return words.charAt(0).toUpperCase() + words.slice(1);
}

export function extractObjective(input: string): string {
  return input.trim();
}

export function generateAcceptanceCriteria(
  synthesis: SynthesisResult,
): string[] {
  const criteria: string[] = ['`pnpm test` passes', '`pnpm typecheck` clean'];
  for (const rec of synthesis.mergedRecommendations) {
    if (rec.priority === 'must') criteria.push(rec.description);
  }
  return criteria;
}

export function generateDoNotChange(extras: readonly string[] = []): string[] {
  const baseline = [
    'System C cost controller (asil-cost-controller)',
  ];
  return [...baseline, ...extras];
}
